package org.example.entities_securitydb;

/**
 * The {@code Role} class represents a specific role stored in the {@code securitydb} database.
 * A {@code Role} object encapsulates the necessary information required to determine an access level or permissions
 * within the telemedicine server. This class encapsulates:
 * <ul>
 *     <li> The unique identifier generated by the database by auto-increment </li>
 *     <li> The name of the role a user can be identified as. May be</li>
 *     <li> {@code ADMIN} - the administrative users with high level permissions</li>
 *     <li> {@code DOCTOR} - medical professionals accessing patient data</li>
 *     <li> {@code PATIENT} - patients accessing their own records</li>
 * </ul>
 *
 * @author MariaMM04
 * @author MamenCortes
 * @author Pblan
 */
public class Role {

    private int id;
    private String rolename;


    /**
     * Creates a {@code Role} empty instance
     */
    public Role() {}

    /**
     * Creates a {@code Role} instance specifying the rolename. This constructor is typically used when
     * creating a {@code Role} instance from scratch into the database.
     *
     * @param rolename  the name of the role the user is
     */
    public Role(String rolename) {
        this.rolename = rolename;
    }

    /**
     * Creates a {@code Role} instance specifying all field values. This constructor is typically used when
     * the {@code Role} instance already exists in the database.
     *
     * @param id
     * @param rolename
     */
    public Role(int id, String rolename) {
        this.id = id;
        this.rolename = rolename;
    }

    // --- Getters and Setters ---
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public String getRolename() { return rolename; }
    public void setRolename(String rolename) { this.rolename = rolename; }


    @Override
    public String toString() {
        return "Role{" +
                "id=" + id +
                ", rolename='" + rolename + '\'' +
                '}';
    }
}
