package org.example.entities_securitydb;

import com.google.gson.JsonObject;

/**
 * The {@code User} class represents a specific user stored in the {@code securitydb} database.
 * A {@code User} object encapsulates the necessary information required to determine an access level or permissions
 * within the telemedicine server. This class encapsulates:
 * <ul>
 *     <li> The unique identifier generated by the database by auto-increment </li>
 *     <li> The user's email address</li>
 *     <li> The user's password</li>
 *     <li> A logical deletion flag to determine if the user is active</li>
 *     <li> Foreign key referencing the {@code Role} role_id</li>
 * </ul>
 *
 * <p>
 *     One point to consider is that the email is going to be linked with a patient email, acting as a
 *     foreign key to the {@link org.example.entities_medicaldb.Patient} class.
 *     Additionally, the password will be encrypted to ensure security.
 * </p>
 *
 * @author MariaMM04
 * @author MamenCortes
 */
public class User {

    private int id;            // Primary key (auto-increment)
    private String email;      // Linked with Patient.email (foreign reference)
    private String password;   // Encrypted or hashed password
    private boolean active;    // Account enabled/disabled flag
    private int role_id;        // Foreign key referencing the Role table

    // Constructors

    /**
     * Creates a {@code User} instance specifying the email, password, role_id and logical flag.
     *
     * @param email     the user's email address
     * @param password  the user's password
     * @param role_id   foreign key identifying the associated role
     * @param active    logical flag whether the user account is active
     */
    public User(String email, String password,int role_id, boolean active) {
        this.email = email;
        this.password = password;
        this.role_id = role_id;
        this.active = active;
    }

    /**
     * Creates a {@code User} instance specifying the email, password and logical flag.
     *
     * @param email     the user's email address
     * @param password  the user's password
     * @param active    logical flag whether the user account is active
     */
    public User(String email, String password,boolean active) {
        this.email = email;
        this.password = password;
        this.active = active;
    }

    /**
     * Creates a {@code User} instance specifying the email, password and role_id.
     *
     * @param email     the user's email address
     * @param password  the user's password
     * @param role_id   foreign key identifying the associated role
     */
    public User(String email, String password, int role_id) {
        this.email = email;
        this.password = password;
        this.role_id = role_id;
        this.active = true;
    }

    /**
     * Creates a {@code User} instance specifying all field values. This constructor is typically used when
     * reconstructing user accounts from database storage.
     *
     * @param id        the user's unique identifier in the database
     * @param email     the user's email address
     * @param password  the user's password
     * @param active    logical flag whether the user is active
     * @param role_id   foreign key identifying the associated role
     */
    public User(int id, String email, String password, boolean active, int role_id) {
        this.id = id;
        this.email = email;
        this.password = password;
        this.role_id = role_id;
        this.active = active;
    }

    // Getters and Setters
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getPassword() { return password; }
    public void setPassword(String password) { this.password = password; }

    public boolean isActive() { return active; }
    public void setActive(boolean active) { this.active = active; }

    public int getRole_id() { return role_id; }
    public void setRole_id(int role_id) { this.role_id = role_id;}

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", email='" + email + '\'' +
                ", password='" + password + '\'' +
                ", active=" + active +
                ", roleId=" + role_id +
                '}';
    }

    /**
     * Converts this {@code User} into a {@link JsonObject}. The JSON object specifies this user's id, email and role
     * //TODO: por que no lo especifica?
     *<p>
     *     Te resulting JSON object deliberately omits the password field to avoid exposing personal information
     *</p>
     *
     * @return  a JSON representation of this user
     *
     * @see JsonObject
     */
    public JsonObject toJason() {
        JsonObject jason = new JsonObject();
        jason.addProperty("id", id);
        jason.addProperty("email", email);
        jason.addProperty("role", role_id); //TODO: change to role name
        return jason;
    }
}
