package org.example.entities_medicaldb;

import com.google.gson.JsonObject;

/**
 * The {@code Doctor} class represents a medical professional entity stored in the medical database {@code medicaldb}.
 * A {@code Doctor} object encapsulates the necessary information to:
 * <ul>
 *     <li> The unique identifier generated by the database </li>
 *     <li> The doctor's name and surname </li>
 *     <li> The doctor's contact information </li>
 *     <li> The doctor's email address </li>
 *     <li> The department the doctor works in</li>
 *     <li> The medical speciality of the doctor</li>
 *     <li> A logical deletion flag to determine if the doctor is active</li>
 * </ul>
 * <p>
 *     Instances of this class can be created either manually by the application or automatically 
 *     reconstructed from database queries or from JSON files received over the network. Conversion utilities 
 *     are provided inside the class {@link #toJason()} and {@link #fromJason(JsonObject)}
 * </p>
 *
 *<p>
 *     An important point to consider is that certain field values will be validated externally when
 *     necessary (e.g., email) for correctness before being assigned to a {@code Doctor}
 *</p>
 *
 * @author MariaMM04
 * @author MamenCortes
 */
public class Doctor {

    // Fields
    private int id;
    private String name;
    private String surname;
    private String contact;
    private String email;
    private String department;
    private String speciality;
    private boolean active;

    /**
     * Creates an empty {@code Doctor} instance
     */
    public Doctor() {}

    /**
     * Creates a {@code Doctor} with personal and contact information
     *
     * @param name      the doctor's name
     * @param surname   the doctor's surname
     * @param contact   the doctor's contact information
     */
    public Doctor(String name, String surname, String contact) {
        this.name = name;
        this.surname = surname;
        this.contact = contact;

    }

    /**
     * Creates a {@code Doctor} instance with most field values specified. Commonly required when registering
     * a doctor into the medical database {@code medicaldb}
     *
     * @param name      the doctor's name
     * @param surname   the doctor's surname
     * @param contact   the doctor's contact information
     * @param email     the doctor's email address
     * @param department    the department in which the doctor works
     * @param speciality    the medical speciality of the doctor
     */
    public Doctor(String name, String surname, String contact, String email,
                  String department, String speciality) {
        this.name = name;
        this.surname = surname;
        this.contact = contact;
        this.email = email;
        this.department = department;
        this.speciality = speciality;
        this.active = true;
    }

    /**
     * Creates a {@code Doctor} instance with all field values specified including the unique database identifier
     * and the active flag. //TODO: para que queremos este constructor?
     *
     * @param id        the unique database identifier for this doctor
     * @param name      the doctor's name
     * @param surname   the doctor's surname
     * @param contact   the doctor's contact information
     * @param email     the doctor's email address
     * @param department    the department in which the doctor works
     * @param speciality    the medical speciality of the doctor
     * @param active    the doctor's active flag. May be
     *                  <code> true </code> if the doctor is active
     *                  <code> false </code> otherwise //TODO: esto esta bien?
     */
    public Doctor(int id, String name, String surname, String contact, String email,
                  String department, String speciality, boolean active) {
        this.id = id;
        this.name = name;
        this.surname = surname;
        this.contact = contact;
        this.email = email;
        this.department = department;
        this.speciality = speciality;
        this.active = active;
    }

    // Getters and Setters
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getSurname() { return surname; }
    public void setSurname(String surname) { this.surname = surname; }

    public String getContact() { return contact; }
    public void setContact(String contact) { this.contact = contact; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getDepartment() { return department; }
    public void setDepartment(String department) { this.department = department; }

    public String getSpeciality() { return speciality; }
    public void setSpeciality(String speciality) { this.speciality = speciality; }

    public boolean isActive() { return active; }
    public void setActive(boolean active) { this.active = active; }

    // --- Utility ---
    @Override
    public String toString() {
        return "Doctor{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", surname='" + surname + '\'' +
                ", contact='" + contact + '\'' +
                ", email='" + email + '\'' +
                ", department='" + department + '\'' +
                ", speciality='" + speciality + '\'' +
                ", active=" + active +
                '}';
    }

    /**
     * Converts this {@code Doctor} into a {@link JsonObject}. The JSON object specifies all public fields
     * except the {@code active} field //TODO: por que no lo especifica?
     *
     * @return  a JSON representation of this doctor
     *
     * @see JsonObject
     */
    public JsonObject toJason() {
        JsonObject json = new JsonObject();
        json.addProperty("id", id);
        json.addProperty("name", name);
        json.addProperty("surname", surname);
        json.addProperty("contact", contact);
        json.addProperty("email", email);
        json.addProperty("department", department);
        json.addProperty("speciality", speciality);
        return json;
    }

    /**
     * Creates a new {@code Doctor} instance from a {@link JsonObject}. The {@code active} field is
     * not included and will default to its initial value.
     *
     * @param json  the JSON object containing this {@code Doctor} data
     * @return  a {@code Doctor} instance from the {@link JsonObject}
     *
     * @see JsonObject
     */
    public static Doctor fromJason(JsonObject json) {
        Doctor doctor = new Doctor();
        doctor.setId(json.get("id").getAsInt());
        doctor.setName(json.get("name").getAsString());
        doctor.setSurname(json.get("surname").getAsString());
        doctor.setContact(json.get("contact").getAsString());
        doctor.setEmail(json.get("email").getAsString());
        doctor.setDepartment(json.get("department").getAsString());
        doctor.setSpeciality(json.get("speciality").getAsString());
        return doctor;
    }
}
