package org.example.entities_medicaldb;

import com.google.gson.JsonObject;

import java.time.LocalDate;

/**
 * The {@code Patient} class represents a patient entity stored in the medical database {@code medicaldb}.
 * A {@code Patient} object encapsulates the necessary information for:
 * <ul>
 *     <li> The unique identifier generated by the database by auto-increment</li>
 *     <li> The patient's name</li>
 *     <li> The patient's surname</li>
 *     <li> The patient's unique email address</li>
 *     <li> The patient's contact information</li>
 *     <li> The patient's date of birth</li>
 *     <li> The patient's biological sex</li>
 *     <li> Logical deletion flag to determine if the patient is active</li>
 *     <li> Foreign key referencing the assigned {@link Doctor} (doctorId)</li>
 *     <li> Foreign key referencing the assigned {@link Doctor} instance</li>
 * </ul>
 *
 * <p>
 *     Instances of this class can be created either manually by the application or automatically
 *     reconstructed from database queries or from JSON files received over the network. Conversion utilities
 *     are provided {@link #toJason()} and {@link #fromJson(JsonObject)}.
 * </p>
 *
 * <p>
 *     An important point to consider is that certain field values will be validated externally when
 *     necessary (e.g., email) for correctness before being assigned to {@code Patient} instance.
 * </p>
 *
 * @author MariaMM04
 * @author MamenCortes
 */
public class Patient {

    private int id;
    private String name;
    private String surname;
    private String email;
    private String contact;
    private LocalDate dateOfBirth;
    private String gender;
    private boolean active;
    private int doctorId;
    private Doctor doctor;


    /**
     * Creates an empty {@code Patient} instance
     */
    public Patient() {}

    /**
     * Creates a {@code Patient} instance with most field values specified
     *
     * @param name      the patient's name
     * @param surname   the patient's surname
     * @param email     the patient's email address
     * @param contact   the patient's contact information
     * @param dateOfBirth   the patient's date of birth
     * @param gender    the patient's gender
     * @param doctorId  foreign key referencing the assigned {@link Doctor} (doctorID)
     */
    public Patient(String name, String surname, String email, String contact,
                   LocalDate dateOfBirth, String gender, int doctorId) {
        this.name = name;
        this.surname = surname;
        this.email = email;
        this.contact = contact;
        this.dateOfBirth = dateOfBirth;
        this.gender = gender;
        this.doctorId = doctorId;
        this.active = true;
        this.doctor = null;
    }

    /**
     * Creates a {@code Patient} instance with all field values specified.
     *
     * @param id        the patient's unique id generated by the database
     * @param name      the patient's name
     * @param surname   the patient's surname
     * @param email     the patient's email address
     * @param contact   the patient's contact information
     * @param dateOfBirth   the patient's date of birth
     * @param gender    the patient's biological sex
     * @param active    the the patient's active flag. May be
     *      *                  <code> true </code> if the doctor is active
     *      *                  <code> false </code> otherwise //TODO: esto esta bien?
     * @param doctorId  the foreign key referencing the {@code Doctor} (doctorId)
     */
    public Patient(int id, String name, String surname, String email, String contact,
                   LocalDate dateOfBirth, String gender, boolean active, int doctorId) {
        this.id = id;
        this.name = name;
        this.surname = surname;
        this.email = email;
        this.contact = contact;
        this.dateOfBirth = dateOfBirth;
        this.gender = gender;
        this.active = active;
        this.doctorId = doctorId;
        this.doctor = null;
    }

    // Getters and Setters
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getSurname() { return surname; }
    public void setSurname(String surname) { this.surname = surname; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getContact() { return contact; }
    public void setContact(String contact) { this.contact = contact; }

    public LocalDate getDateOfBirth() { return dateOfBirth; }
    public void setDateOfBirth(LocalDate dateOfBirth) { this.dateOfBirth = dateOfBirth; }

    public String getGender() { return gender; }
    public void setGender(String gender) { this.gender = gender; }

    public boolean isActive() { return active; }
    public void setActive(boolean active) { this.active = active; }

    public int getDoctorId() { return doctorId; }
    public void setDoctorId(int doctorId) { this.doctorId = doctorId; }

    public Doctor getDoctor() {
        return doctor;
    }

    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }

    @Override
    public String toString() {
        return "Patient{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", surname='" + surname + '\'' +
                ", email='" + email + '\'' +
                ", contact='" + contact + '\'' +
                ", dateOfBirth=" + dateOfBirth +
                ", gender='" + gender + '\'' +
                ", active=" + active +
                ", doctorId=" + doctorId +
                '}';
    }

    /**
     * Converts this {@code Patient} into a {@link JsonObject}. The JSON object specifies all public fields
     * except the {@code active} field //TODO: por que no lo especifica?
     *
     * @return  a JSON representation of this patient
     *
     * @see JsonObject
     */
    public JsonObject toJason() {
        JsonObject jason = new JsonObject();
        jason.addProperty("id", id);
        jason.addProperty("name", name);
        jason.addProperty("surname", surname);
        jason.addProperty("email", email);
        jason.addProperty("contact", contact);
        jason.addProperty("dateOfBirth", dateOfBirth.toString());
        jason.addProperty("gender", gender);
        jason.addProperty("active", active);
        jason.addProperty("doctorId", doctorId);
        return jason;
    }

    /**
     * Creates a new {@code Patient} instance from a {@link JsonObject}. The {@code active} field is
     * not included and will default to its initial value.
     *
     * @param jason  the JSON object containing this {@code Patient} data
     * @return  a {@code Doctor} instance from the {@link JsonObject}
     *
     * @see JsonObject
     */
    public static Patient fromJson(JsonObject jason) {
        Patient patient = new Patient();
        patient.setId(jason.get("id").getAsInt());
        patient.setName(jason.get("name").getAsString());
        patient.setSurname(jason.get("surname").getAsString());
        patient.setEmail(jason.get("email").getAsString());
        patient.setContact(jason.get("contact").getAsString());
        patient.setDateOfBirth(LocalDate.parse(jason.get("dateOfBirth").getAsString()));
        patient.setGender(jason.get("gender").getAsString());
        patient.setDoctorId(jason.get("doctorId").getAsInt());
        return patient;
    }
}
