package org.example.entities_medicaldb;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 * The {@code Report} class represents a medical report stored in the medical database {@code medicaldb}.
 * A {@code Report} contains the information documented by the doctor as part of a patient evaluation. The {@code Report}
 * object encapsulates:
 * <ul>
 *     <li> The unique identifier generated by the database by auto-increment </li>
 *     <li> The date on which the report was documented</li>
 *     <li> A list of symptoms reported by the patient
 *     <li> The foreign key referencing the associated patient {@code Patient} (patientId)</li>
 *     <li> The foreign key referencing the associated doctor {@code Doctor} (doctorId)</li>
 *     <li> Additional comments or clinical observations</li>
 *     <li> A logical deletion flag indicating whether the report is active</li>
 * </ul>
 *
 * <p>
 *     Instances of this class are typically created after a doctor's consultation or patient's evaluation and records
 *     the patient's symptoms, notes and other relevant clinical findings.
 *     This class does not perform validation on field values.
 * </p>
 *
 * @author MariaMM04
 */
public class Report {

    // --- Enum for possible patient symptoms ---

    /**
     * The {@code Symptoms} enumeration defines the set of possible symptoms that can be recorded in a
     * {@link Report} instance.
     * This enumeration includes:
     * <ul>
     *     <li> Headache reported by the patient</li>
     *     <li> Dizziness sensations</li>
     *     <li> Tremors or involuntary shacking</li>
     *     <li> Nausea or stomach discomfort</li>
     *     <li> Previous loss of consciousness of the patient</li>
     *     <li> Irregular or rapid heartbeat sensations</li>
     *     <li> Any symptom not represented by the predefined constants</li>
     * </ul>
     */
    public enum Symptom {
        Muscle_Stiffness,
        Trouble_Breathing,
        Sudden_Unconsciousness,
        Auditory_Hallucinations,
        Anxiety,
        Deja_vu,
        Short_term_confusion,
        Dizziness,
        Loss_off_balance,
        Fear,
        Nausea,
        Muscle_spasms,
        Fatigue,
        None
    }

    private int id;                  // Primary key (auto-increment)
    private LocalDate date;          // Date of the report
    private List<Symptom> symptoms;  // List of selected symptoms (enum)
    private int patientId;           // Foreign key referencing Patient

    //Constructors

    /**
     * Creates an empty {@code Report} instance
     */
    public Report() {}

    /**
     * Creates a {@code Report} instance with most of the field values specified. Typically used when creating a new
     * {@code Report} object that does not exist in the database.
     *
     * @param date      the date of which the report was created
     * @param symptoms  the set of selected symptoms
     * @param patientId foreign key referencing a {@code Patient} patientId
     */
    public Report(LocalDate date, List<Symptom> symptoms, int patientId) {
        this.date = date;
        this.symptoms = symptoms;
        this.patientId = patientId;
    }

    /**
     * Creates a {@code Report} instance with all field values specified. This is typically used when reconstructing
     * a {@code Report} object that already exists in the database
     *
     * @param id        the report's unique identifier generated by the database
     * @param date      the date of which the report was created
     * @param symptoms  the set of selected symptoms in the report
     * @param patientId foreign key referencing a {@code Patient} patientId
     */
    public Report(int id, LocalDate date, List<Symptom> symptoms, int patientId) {
        this.id = id;
        this.date = date;
        this.symptoms = symptoms;
        this.patientId = patientId;
    }

    // Getters and Setters
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public LocalDate getDate() { return date; }
    public void setDate(LocalDate date) { this.date = date; }

    public List<Symptom> getSymptoms() { return symptoms; }
    public void setSymptoms(List<Symptom> symptoms) { this.symptoms = symptoms; }
    public void addSymptom(Symptom symptom) {this.symptoms.add(symptom);}

    public int getPatientId() { return patientId; }
    public void setPatientId(int patientId) { this.patientId = patientId; }

    // --- Utility ---
    @Override
    public String toString() {
        return "Report{" +
                "id=" + id +
                ", date=" + date +
                ", symptoms=" + symptoms +
                ", patientId=" + patientId +
                '}';
    }

    /**
     * Converts this {@code Report} into a {@link JsonObject}.
     *
     * @return  a JSON representation of this report
     *
     * @see JsonObject
     */
    public JsonObject toJson() {
        JsonObject jsonObject = new JsonObject();
        jsonObject.addProperty("id", id);
        jsonObject.addProperty("date", date.toString());
        jsonObject.addProperty("patientId", patientId);
        JsonArray symptomsJsonArray = new JsonArray();
        for(Symptom symptom : symptoms) {
            symptomsJsonArray.add(symptom.name());
        }
        jsonObject.add("symptoms", symptomsJsonArray);
        return jsonObject;
    }

    /**
     * Creates a new {@code Report} instance from a {@link JsonObject}
     *
     * @param jsonObject  the JSON object containing this {@code Report} data
     * @return  a {@code Report} instance from the {@link JsonObject}
     *
     * @see JsonObject
     */
    public static Report fromJson(JsonObject jsonObject) {
        Report report = null;
        try{
            report = new Report();
            report.setId(jsonObject.get("id").getAsInt());
            report.setDate(LocalDate.parse(jsonObject.get("date").getAsString()));
            JsonArray symptomsJsonArray = jsonObject.get("symptoms").getAsJsonArray();
            List<Report.Symptom> symptoms = new ArrayList<>();
            for(JsonElement elem : symptomsJsonArray) {
                symptoms.add(Report.Symptom.valueOf(elem.getAsString()));
            }
            report.setSymptoms(symptoms);
        }catch(Exception ex){
            System.out.println("Error parsing report");
        }

        return report;
    }
}


