package org.example.entities_medicaldb;

import com.google.gson.JsonElement;

import java.io.File;
import java.time.LocalDate;

/**
 * The {@code Signal} class represents a signal entity stored in the medical database {@code medicaldb}.
 * A {@code Signal} object encapsulates the necessary information to:
 * <ul>
 *     <li> The unique identifier generated by the database by auto-increment </li>
 *     <li> The file where the signal is contained </li>
 *     <li> The date of the signal recording </li>
 *     <li> The comments about the signal </li>
 *     <li> The foreign key referencing the {@code Patient} (patientId)</li>
 *     <li> The sampling frequency of the signal</li>
 * </ul>
 * <p>
 *     Instances of this class are typically reconstructed from metadata sent by the patient's device over the network.
 *     When the patient sends over the signal (such as ECG or accelerometer data), the server receives multiple
 *     field values including the file compressed, recording date and sampling frequency. These values are used to create
 *     a new {@code Signal} instance for storage in the database.
 * </p>
 *
 * @author MariaMM04
 *
 */
public class Signal {

    private int id;
    private File path;
    private LocalDate date;
    private String comments;
    private int patientId;
    private double sampleFrequency;

    /**
     * Creates an empty {@code Signal} instance with all field values of ServerMetadata specified. This constructor is typically used
     *      * when reconstructing a {@code Signal} object that was received form the connexion of the patient, only the metadata, not with the file.
     * @param signalId      the signal's unique id generated by the database
     * @param date      the date of the recording of the signal
     * @param comments  optional comments regarding the signal, normally empty if received from the patient as it is intended to be filled by the doctor
     * @param patientId the foreign key referencing the {@code Patient} (patientId)
     * @param samplingFrequency   the signal's sampling frequency
     *
     */
    public Signal(int signalId, LocalDate date, String comments, int patientId, int samplingFrequency) {
        this.id=signalId;
        this.date=date;
        this.comments=comments;
        this.patientId=patientId;
        this.sampleFrequency=samplingFrequency;
    }

    /**
     * Creates a {@code Signal} instance with all field values specified. This constructor is typically used
     * when reconstructing a {@code Signal} object that already exist in the database.
     *
     * @param id        the signal's unique id generated by the database
     * @param path      the file compressed where the signal is sent
     * @param date      the date of the recording of the signal
     * @param comments  optional comments regarding the signal
     * @param patientId the foreign key referencing the {@code Patient} (patientId)
     * @param sampleFrequency   the signal's sampling frequency
     */
    public Signal(int id, File path, LocalDate date, String comments, int patientId, double sampleFrequency) {
        this.id = id;
        this.path = path;
        this.date = date;
        this.comments = comments;
        this.patientId = patientId;
        this.sampleFrequency = sampleFrequency;

    }

    /**
     * Creates a {@code Signal} instance with most field values specified. This constructor is typically used
     * when creating a new object that does not exist in the database.
     *
     * @param path      the file compressed where the signal is sent
     * @param date      the date of the recording of the signal
     * @param comments  optional comments regarding the evaluation of the signal
     * @param patientId the foreign key referencing the {@code Patient} patientId
     * @param sampleFrequency   the signal's sampling frequency
     */
    public Signal(File path, LocalDate date, String comments, int patientId, double  sampleFrequency) {
        this.path = path;
        this.date = date;
        this.comments = comments;
        this.patientId = patientId;
        this.sampleFrequency = sampleFrequency;

    }

    // Getters and Setters
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public File getPath() { return path; }
    public void setPath(File path) { this.path = path; }

    public LocalDate getDate() { return date; }
    public void setDate(LocalDate date) { this.date = date; }

    public String getComments() { return comments; }
    public void setComments(String comments) { this.comments = comments; }

    public int getPatientId() { return patientId; }
    public void setPatientId(int patientId) { this.patientId = patientId; }

    public double getSampleFrequency() { return sampleFrequency; }
    public void setSampleFrequency(double sampleFrequency) { this.sampleFrequency = sampleFrequency; }
    // --- Utility ---
    public byte[] decompessSignalFile() {
        // Placeholder for decompression logic
        return new byte[0];
    }

    @Override
    public String toString() {
        return "Signal{" +
                "id=" + id +
                ", path='" + path.getName() + '\'' +
                ", date=" + date +
                ", comments='" + comments + '\'' +
                ", patientId=" + patientId +
                ", sampleFrequency=" + sampleFrequency +
                '}';
    }

}
