package org.example.entities_medicaldb;

import java.time.LocalDate;

/**
 * The {@code Signal} class represents a signal entity stored in the medical database {@code medicaldb}.
 * A {@code Signal} object encapsulates the necessary information to:
 * <ul>
 *     <li> The unique identifier generated by the database by auto-increment </li>
 *     <li> The path where the signal is sent </li> //TODO: es saved or contained?
 *     <li> The date of the signal recording </li>
 *     <li> The comments about the signal </li>
 *     <li> The foreign key referencing the {@code Patient} (patientId)</li>
 *     <li> The sampling frequency of the signal</li>
 * </ul>
 * <p>
 *     Instances of this class are typically reconstructed from metadata sent by the patient's device over the network.
 *     When the patient sends over the signal (such as ECG or accelerometer data), the server receives multiple
 *     field values including the file path, recording date and sampling frequency. These values are used to create
 *     a new {@code Signal} instance for storage in the database.
 * </p>
 *
 * @author MariaMM04
 *
 */
public class Signal {

    private int id;
    private String path;
    private LocalDate date;
    private String comments;
    private int patientId;
    private double sampleFrequency;

    /**
     * Creates an empty {@code Signal} instance
     */
    public Signal() {}

    /**
     * Creates a {@code Signal} instance with all field values specified. This constructor is typically used
     * when reconstructing a {@code Signal} object that already exist in the database.
     *
     * @param id        the signal's unique id generated by the database
     * @param path      the file path where the signal is sent
     * @param date      the date of the recording of the signal
     * @param comments  optional comments regarding the signal
     * @param patientId the foreign key referencing the {@code Patient} (patientId)
     * @param sampleFrequency   the signal's sampling frequency
     */
    public Signal(int id, String path, LocalDate date, String comments, int patientId, double sampleFrequency) {
        this.id = id;
        this.path = path;
        this.date = date;
        this.comments = comments;
        this.patientId = patientId;
        this.sampleFrequency = sampleFrequency;

    }

    /**
     * Creates a {@code Signal} instance with most field values specified. This constructor is typically used
     * when creating a new object that does not exist in the database.
     *
     * @param path      the file path where the signal is sent
     * @param date      the date of the recording of the signal
     * @param comments  optional comments regarding the evaluation of the signal
     * @param patientId the foreign key referencing the {@code Patient} patientId
     * @param sampleFrequency   the signal's sampling frequency
     */
    public Signal(String path, LocalDate date, String comments, int patientId, double  sampleFrequency) {
        this.path = path;
        this.date = date;
        this.comments = comments;
        this.patientId = patientId;
        this.sampleFrequency = sampleFrequency;

    }

    // Getters and Setters
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public String getPath() { return path; }
    public void setPath(String path) { this.path = path; }

    public LocalDate getDate() { return date; }
    public void setDate(LocalDate date) { this.date = date; }

    public String getComments() { return comments; }
    public void setComments(String comments) { this.comments = comments; }

    public int getPatientId() { return patientId; }
    public void setPatientId(int patientId) { this.patientId = patientId; }

    public double getSampleFrequency() { return sampleFrequency; }
    public void setSampleFrequency(double sampleFrequency) { this.sampleFrequency = sampleFrequency; }


    @Override
    public String toString() {
        return "Signal{" +
                "id=" + id +
                ", path='" + path + '\'' +
                ", date=" + date +
                ", comments='" + comments + '\'' +
                ", patientId=" + patientId +
                ", sampleFrequency=" + sampleFrequency +
                '}';
    }
}
